// <auto-generated />
namespace MyReklama.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addвбодиордерсервис : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addвбодиордерсервис));
        
        string IMigrationMetadata.Id
        {
            get { return "202003110720141_add в боди ордер сервис"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
